[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "oreshicrecord"
version = "0.0.1"
requires-python = ">=3.8"

[project.scripts]
ors = "ors.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ors*"]

